name: "Github Actions Controller"
description: "Pull & Update specific workflows into a repository"

inputs:
  pull_testing_workflows:
    description: "Workflows for running testing of your code"
    default: "false"
  pull_linting_workflows:
    description: "Workflows for linting your code"
    default: "false"
  pull_build_workflows:
    description: "Workflows for building your code"
    default: "false"
  pull_deployment_workflows:
    description: "Workflows for deploying your code"
    default: "false"
  base_branch:
    description: "Base branch to create PR against"
    default: "main"
  templates_repo:
    description: "Repository containing workflow templates"
    default: "BenFielder/github-actions-controller"
  app_id:
    description: "GitHub App ID"
    required: true
  app_private_key:
    description: "GitHub App Private Key"
    required: true

runs:
  using: "composite"
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Debug inputs
      run: |
        echo "App ID length: ${#APP_ID}"
        echo "App ID (first 3 chars): ${APP_ID:0:3}"
        echo "Private key length: ${#PRIVATE_KEY}"
        echo "Private key (first 20 chars): ${PRIVATE_KEY:0:20}"
      shell: bash
      env:
        APP_ID: ${{ inputs.app_id }}
        PRIVATE_KEY: ${{ inputs.app_private_key }}

    - name: Generate GitHub App Token
      id: generate_token
      uses: actions/create-github-app-token@v2.0.2
      with:
          app-id: ${{ inputs.app_id }}
          private-key: ${{ inputs.app_private_key }}

    - name: Run controller logic
      run: |
        bash "${{ github.action_path }}/src/scripts/pull_workflows.sh" \
          "${{ inputs.pull_testing_workflows }}" \
          "${{ inputs.pull_linting_workflows }}" \
          "${{ inputs.pull_build_workflows }}" \
          "${{ inputs.pull_deployment_workflows }}" \
          "${{ inputs.base_branch }}" \
          "${{ inputs.templates_repo }}"
      env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      shell: bash